module: cloud-sdk-ios-fioriarkit
author: SAP SE
author_url: https://www.sap.com
theme: jony
copyright: '© 2020 [https://github.com/SAP/cloud-sdk-ios-fioriarkit](https://github.com/SAP/cloud-sdk-ios-fioriarkit) under Apache-2.0.'
hide_documentation_coverage: true
