module: cloud-sdk-ios-fiori-ar
author: SAP SE
author_url: https://www.sap.com
theme: jony
copyright: '© 2020 [https://github.com/SAP/cloud-sdk-ios-fiori-ar](https://github.com/SAP/cloud-sdk-ios-fiori-ar) under Apache-2.0.'
hide_documentation_coverage: true

custom_categories:

  - name: Annotation Viewing
    children:
    - ARAnnotationsView
    - ARScanView
    - MarkerView
    - CardView

  - name: Scene Authoring
    children:
    - SceneAuthoringView
    - SceneEditing
    - SceneIdentifyingAttribute

  - name: Annotation Management
    children:
    - ARAnnotationViewModel
    - ARManager

  - name: Annotation Data Loading
    children:
    - AnnotationLoadingStrategy
    - AsyncAnnotationLoadingStrategy
    - RCProjectStrategy
    - RealityFileStrategy
    - ServiceStrategy
    - UsdzFileStrategy
    - VectorStrategy

  - name: Models
    children:
    - CardItemModel
    - CodableCardItem
    - ScreenAnnotation
    - MarkerControl
    - CardImage
