//
// Generated by SwagGen with template `SwiftSAPURLSession`
// https://github.com/MarcoEidinger/SwagGen/tree/foundation/SwiftSAPURLSession
//

import Foundation

extension ARService.Scene {

    /**
    Find scene by ID

    Returns a single scene
    */
    internal enum GetSceneById {

        internal static let service = APIService<Response>(id: "getSceneById", tag: "scene", method: "GET", path: "/scene/{sceneId}", hasBody: false)

        internal final class Request: APIRequest<Response> {

            internal struct Options {

                /** ID of scene to return */
                internal var sceneId: String

                /** Language */
                internal var locale: String?

                internal init(sceneId: String, locale: String? = nil) {
                    self.sceneId = sceneId
                    self.locale = locale
                }
            }

            internal var options: Options

            internal init(options: Options) {
                self.options = options
                super.init(service: GetSceneById.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            internal convenience init(sceneId: String, locale: String? = nil) {
                let options = Options(sceneId: sceneId, locale: locale)
                self.init(options: options)
            }

            internal override var path: String {
                return super.path.replacingOccurrences(of: "{" + "sceneId" + "}", with: "\(self.options.sceneId)")
            }

            internal override var queryParameters: [String: Any] {
                var params: [String: Any] = [:]
                if let locale = options.locale {
                  params["locale"] = locale
                }
                return params
            }
        }

        internal enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            internal typealias SuccessType = Scene

            /** successful operation */
            case status200(Scene)

            /** Invalid ID supplied */
            case status400

            /** Scene not found */
            case status404

            internal var success: Scene? {
                switch self {
                case .status200(let response): return response
                default: return nil
                }
            }

            internal var response: Any {
                switch self {
                case .status200(let response): return response
                default: return ()
                }
            }

            internal var statusCode: Int {
                switch self {
                case .status200: return 200
                case .status400: return 400
                case .status404: return 404
                }
            }

            internal var successful: Bool {
                switch self {
                case .status200: return true
                case .status400: return false
                case .status404: return false
                }
            }

            internal init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(Scene.self, from: data))
                case 400: self = .status400
                case 404: self = .status404
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            internal var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            internal var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
