//
// Generated by SwagGen with template `SwiftSAPURLSession`
// https://github.com/MarcoEidinger/SwagGen/tree/foundation/SwiftSAPURLSession
//

import Foundation

extension ARService.Scene {

    /**
    Find scenes by Aliases

    Returns multiple scene
    */
    internal enum GetScenesByAliases {

        internal static let service = APIService<Response>(id: "getScenesByAliases", tag: "scene", method: "GET", path: "/scene/findByAlias", hasBody: false)

        internal final class Request: APIRequest<Response> {

            internal struct Options {

                /** Language */
                internal var language: String?

                internal init(language: String? = nil) {
                    self.language = language
                }
            }

            internal var options: Options

            internal init(options: Options) {
                self.options = options
                super.init(service: GetScenesByAliases.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            internal convenience init(language: String? = nil) {
                let options = Options(language: language)
                self.init(options: options)
            }

            internal override var queryParameters: [String: Any] {
                var params: [String: Any] = [:]
                if let language = options.language {
                  params["language"] = language
                }
                return params
            }
        }

        internal enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            internal typealias SuccessType = Scene

            /** successful operation */
            case status200(Scene)

            /** Invalid Alias supplied */
            case status400

            /** Scene not found */
            case status404

            internal var success: Scene? {
                switch self {
                case .status200(let response): return response
                default: return nil
                }
            }

            internal var response: Any {
                switch self {
                case .status200(let response): return response
                default: return ()
                }
            }

            internal var statusCode: Int {
                switch self {
                case .status200: return 200
                case .status400: return 400
                case .status404: return 404
                }
            }

            internal var successful: Bool {
                switch self {
                case .status200: return true
                case .status400: return false
                case .status404: return false
                }
            }

            internal init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(Scene.self, from: data))
                case 400: self = .status400
                case 404: self = .status404
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            internal var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            internal var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
