//
// Generated by SwagGen with template `SwiftSAPURLSession`
// https://github.com/MarcoEidinger/SwagGen/tree/foundation/SwiftSAPURLSession
//

import Foundation

extension ARService.AnnotationAnchor {

    /**
    Find annotationAnchors by Scene

    Returns an array of annotationAnchors
    */
    internal enum GetAnnotationAnchorsByScene {

        internal static let service = APIService<Response>(id: "getAnnotationAnchorsByScene", tag: "annotationAnchor", method: "GET", path: "/annotationAnchor/findByScene", hasBody: false)

        internal final class Request: APIRequest<Response> {

            internal struct Options {

                /** ID of scene */
                internal var sceneId: String?

                /** Alias of scene */
                internal var sceneAlias: String?

                /** Language */
                internal var locale: String?

                internal init(sceneId: String? = nil, sceneAlias: String? = nil, locale: String? = nil) {
                    self.sceneId = sceneId
                    self.sceneAlias = sceneAlias
                    self.locale = locale
                }
            }

            internal var options: Options

            internal init(options: Options) {
                self.options = options
                super.init(service: GetAnnotationAnchorsByScene.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            internal convenience init(sceneId: String? = nil, sceneAlias: String? = nil, locale: String? = nil) {
                let options = Options(sceneId: sceneId, sceneAlias: sceneAlias, locale: locale)
                self.init(options: options)
            }

            internal override var queryParameters: [String: Any] {
                var params: [String: Any] = [:]
                if let sceneId = options.sceneId {
                  params["sceneId"] = sceneId
                }
                if let sceneAlias = options.sceneAlias {
                  params["sceneAlias"] = sceneAlias
                }
                if let locale = options.locale {
                  params["locale"] = locale
                }
                return params
            }
        }

        internal enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            internal typealias SuccessType = [AnnotationAnchor]

            /** successful operation */
            case status200([AnnotationAnchor])

            /** Invalid ID supplied */
            case status400

            /** AnnotationAnchors for scene not found */
            case status404

            internal var success: [AnnotationAnchor]? {
                switch self {
                case .status200(let response): return response
                default: return nil
                }
            }

            internal var response: Any {
                switch self {
                case .status200(let response): return response
                default: return ()
                }
            }

            internal var statusCode: Int {
                switch self {
                case .status200: return 200
                case .status400: return 400
                case .status404: return 404
                }
            }

            internal var successful: Bool {
                switch self {
                case .status200: return true
                case .status400: return false
                case .status404: return false
                }
            }

            internal init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode([AnnotationAnchor].self, from: data))
                case 400: self = .status400
                case 404: self = .status404
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            internal var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            internal var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
