//
// Generated by SwagGen with template `SwiftSAPURLSession`
// https://github.com/MarcoEidinger/SwagGen/tree/foundation/SwiftSAPURLSession
//

import Foundation

extension ARService.File {

    /**
    Get file data (reality, usdz or image) by id

    Returns contents of a file
    */
    internal enum GetFileById {

        internal static let service = APIService<Response>(id: "getFileById", tag: "file", method: "GET", path: "/file/{fileId}", hasBody: false)

        internal final class Request: APIRequest<Response> {

            internal struct Options {

                /** ID of file */
                internal var fileId: String

                internal init(fileId: String) {
                    self.fileId = fileId
                }
            }

            internal var options: Options

            internal init(options: Options) {
                self.options = options
                super.init(service: GetFileById.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            internal convenience init(fileId: String) {
                let options = Options(fileId: fileId)
                self.init(options: options)
            }

            internal override var path: String {
                return super.path.replacingOccurrences(of: "{" + "fileId" + "}", with: "\(self.options.fileId)")
            }
        }

        internal enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            internal typealias SuccessType = File

            /** successful operation */
            case status200(File)

            /** Invalid ID supplied */
            case status400

            /** File not found */
            case status404

            internal var success: File? {
                switch self {
                case .status200(let response): return response
                default: return nil
                }
            }

            internal var response: Any {
                switch self {
                case .status200(let response): return response
                default: return ()
                }
            }

            internal var statusCode: Int {
                switch self {
                case .status200: return 200
                case .status400: return 400
                case .status404: return 404
                }
            }

            internal var successful: Bool {
                switch self {
                case .status200: return true
                case .status400: return false
                case .status404: return false
                }
            }

            internal init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(data)
                case 400: self = .status400
                case 404: self = .status404
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            internal var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            internal var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
