//
// Generated by SwagGen with template `SwiftSAPURLSession`
// https://github.com/MarcoEidinger/SwagGen/tree/sap/Swift-SAPURLSession
//

import Foundation

/** A runtime API schema to store Augmented Reality (AR) scenes and annotations. This API schema only provide API for client SDK calling. */
internal struct ARService {

    /// Whether to discard any errors when decoding optional properties
    internal static var safeOptionalDecoding = false

    /// Whether to remove invalid elements instead of throwing when decoding arrays
    internal static var safeArrayDecoding = false

    /// Used to encode Dates when uses as string params
    internal static var dateEncodingFormatter = DateFormatter(formatString: "yyyy-MM-dd'T'HH:mm:ssZZZZZ",
                                                            locale: Locale(identifier: "en_US_POSIX"),
                                                            calendar: Calendar(identifier: .gregorian))

    internal static let version = "0.0.1"

    internal enum AnnotationAnchor {}
    internal enum File {}
    internal enum Scene {}

    internal enum Server {

        internal static let main = "/augmentedreality/v1/runtime"
    }
}
