//
// Generated by SwagGen with template `SwiftSAPURLSession`
// https://github.com/MarcoEidinger/SwagGen/tree/sap/Swift-SAPURLSession
//

import Foundation

internal enum APIClientError: Error {
    case unexpectedStatusCode(statusCode: Int, data: Data? = nil)
	case encodingError(Error)
    case decodingError(DecodingError)
    case requestEncodingError(Error)
    case validationError(Error)
    case networkError(Error)
    case unknownError(Error)
    case failure(HTTPResponseStatus)

    internal var name:String {
        switch self {
        case .unexpectedStatusCode: return "Unexpected status code"
        case .encodingError: return "Encoding error"
        case .decodingError: return "Decoding error"
        case .validationError: return "Request validation failed"
        case .requestEncodingError: return "Request encoding failed"
        case .networkError: return "Network error"
        case .unknownError: return "Unknown error"
        case .failure(let httpResponseStatus): return "Status code \(httpResponseStatus.code)"
        }
    }
}

extension APIClientError: CustomStringConvertible {

    internal var description:String {
        switch self {
        case .unexpectedStatusCode(let statusCode, _): return "\(name): \(statusCode)"
        case .encodingError(let error): return "\(name): \(error.localizedDescription)\n\(error)"
        case .decodingError(let error): return "\(name): \(error.localizedDescription)\n\(error)"
        case .validationError(let error): return "\(name): \(error.localizedDescription)"
        case .requestEncodingError(let error): return "\(name): \(error)"
        case .networkError(let error): return "\(name): \(error.localizedDescription)"
        case .unknownError(let error): return "\(name): \(error.localizedDescription)"
        case .failure(let httpResponseStatus): return "\(name): \(httpResponseStatus.description)"
        }
    }
}
