//
// Generated by SwagGen with template `SwiftSAPURLSession`
// https://github.com/MarcoEidinger/SwagGen/tree/sap/Swift-SAPURLSession
//

internal struct APIService<ResponseType: APIResponseValue> {

    internal let id: String
    internal let tag: String
    internal let method: String
    internal let path: String
    internal let hasBody: Bool
    internal let isUpload: Bool

    internal init(id: String, tag: String = "", method:String, path:String, hasBody: Bool, isUpload: Bool = false) {
        self.id = id
        self.tag = tag
        self.method = method
        self.path = path
        self.hasBody = hasBody
        self.isUpload = isUpload
    }
}

extension APIService: CustomStringConvertible {

    internal var name: String {
        return "\(tag.isEmpty ? "" : "\(tag).")\(id)"
    }

    internal var description: String {
        return "\(name): \(method) \(path)"
    }
}

internal struct SecurityRequirement {
    internal let type: String
    internal let scopes: [String]

    internal init(type: String, scopes: [String]) {
        self.type = type
        self.scopes = scopes
    }
}

