//
// Generated by SwagGen with template `SwiftSAPURLSession`
// https://github.com/MarcoEidinger/SwagGen/tree/sap/Swift-SAPURLSession
//

import Foundation

extension ARService.Scene {

    /** Delete an existing scene */
    internal enum DeleteScene {

        internal static let service = APIService<Response>(id: "deleteScene", tag: "scene", method: "DELETE", path: "/scene/{sceneId}", hasBody: false)

        internal final class Request: APIRequest<Response> {

            internal struct Options {

                /** ID of scene to delete */
                internal var sceneId: Int

                internal init(sceneId: Int) {
                    self.sceneId = sceneId
                }
            }

            internal var options: Options

            internal init(options: Options) {
                self.options = options
                super.init(service: DeleteScene.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            internal convenience init(sceneId: Int) {
                let options = Options(sceneId: sceneId)
                self.init(options: options)
            }

            internal override var path: String {
                return super.path.replacingOccurrences(of: "{" + "sceneId" + "}", with: "\(self.options.sceneId)")
            }
        }

        internal enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            internal typealias SuccessType = Void

            /** successful operation */
            case status204

            /** Business user is not authenticated */
            case status401

            /** Forbidden to delete, only creator user can delete his own scene */
            case status403

            /** Scene not found */
            case status404

            /** Invalid request path or method */
            case status405

            /** Server internal error */
            case status500

            internal var success: Void? {
                switch self {
                case .status204: return ()
                default: return nil
                }
            }

            internal var response: Any {
                switch self {
                default: return ()
                }
            }

            internal var statusCode: Int {
                switch self {
                case .status204: return 204
                case .status401: return 401
                case .status403: return 403
                case .status404: return 404
                case .status405: return 405
                case .status500: return 500
                }
            }

            internal var successful: Bool {
                switch self {
                case .status204: return true
                case .status401: return false
                case .status403: return false
                case .status404: return false
                case .status405: return false
                case .status500: return false
                }
            }

            internal init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 204: self = .status204
                case 401: self = .status401
                case 403: self = .status403
                case 404: self = .status404
                case 405: self = .status405
                case 500: self = .status500
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            internal var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            internal var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
