name: PR

on:
  pull_request:
    types: [opened, synchronize]


jobs:

  swift-api-assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: MarcoEidinger/swift-api-assign-reviewer@1.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/configActions/swift-api-assign-reviewer.yml"

  conventionalcommit-verification:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v1
        with:
            configFile: '.github/configActions/commitlint.config.js'

  ReuseComplianceCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1.1

  CodeFormattingCheck:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'Sources/**'
      - name: Cache Mint packages
        id: mint-cache
        if: steps.changes.outputs.Sources == 'true'
        uses: actions/cache@v2
        with:
          path: /usr/local/lib/mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: ${{ runner.os }}-mint-
      - name: Install Mint
        if: steps.changes.outputs.src == 'true'
        run: |
          brew upgrade mint || brew install mint || true
      - name: Install swiftformat via mint
        if: steps.mint-cache.outputs.cache-hit != 'true' && steps.changes.outputs.src == 'true'
        run: mint bootstrap
      - name: Format Swift code
        if: steps.changes.outputs.src == 'true'
        run: mint run swiftformat --verbose .
      - name: Verify formatted code is unchanged
        if: steps.changes.outputs.src == 'true'
        run: git diff --exit-code HEAD
